### PR TITLE
Refined formant tracks

### PR DESCRIPTION
**Pull request by MichaelGoodale**
This PR adds an option to the refined formants function to save tracks in the database rather than just individual points.

### CODE REVIEW

**Comment by MichaelGoodale** [comment]
Note, one other thing I was unsure about in this is whether bandwidth should be saved as well, and if it's saved should it be saved as part of the formant track, or a different track.

**Comment by msonderegger** [comment]
@MichaelGoodale Belatedly: in principle I think we want the option of both bandwidth and amplitude tracks. This would parallel the formant-point-measurement functionality, where F1/F2/F3 are saved as token properties along with A1/A2/A3 and B1/B2/B3 (and "AX"? not sure what that is).   If we did this, B1 should definitely be saved as its own track, and so on -- not as part of the formant track.... assuming I understand the current implementation right for token-level measurements -- F1 and B1 are not part of the same subannotation?

In practice, let's see how the current formant track implementation does in some practical cases before exploding the number of tracks from 3 to 9.

@jeffmielke do you have thoughts on this?

**Comment by jeffmielke** [comment]
@msonderegger and @MichaelGoodale I would extract
F1,F2,F3,B1,B2,B3,A1,A2,A3 at each time point. AX is the amplitude of the
formant that was dropped (it's A4 if no formant was dropped, the amplitude
of the false formant between F1 and F2 if the measured F2 was dropped,
etc.) It's useful for evaluating the drop-formant scheme but not something
to analyze beyond that. I could see it being useful for evaluating whether
a false formant appears to be false throughout the duration of the vowel,
but not for any linguistic questions I can think of.

I don't know what a subannotation is here.

Is your plan for the 9 measurements to be at 5%, 10%, ..., 95%? That would
be good.



Jeff Mielke
Associate professor
Linguistics program
Department of English
North Carolina State University

**Comment by msonderegger** [comment]
OK, so it sounds like we will want to keep all 9 tracks eventually.  @MichaelGoodale I leave it to you whether to first get things working and tested on 3 tracks alone (F1/F2/F3) or on all 9.

@jeffmielke I am not sure where the measurements are... I'm assuming wherever they are for the formant tracks that were already being calculated for the formant point estimates. MG, could you clarify?

Sub-annotation: not so important, it's the Polyglot/ISCAN term for a property of linguistic objects that would in phonetics usually be called an "annotation" -- a point measurement or tuple, like F1 or VOT.  some minimal descriptiopn here:
https://polyglotdb.readthedocs.io/en/latest/queries_annotations.html?highlight=subannotation#subannotations

Perhaps confusingly, the name "annotations" is reserved for linguistic objects that are in the graph database as nodes: phones, words, etc.  This is because the formalism (Bird & Liberman) is called "annotation graphs".

**Comment by jeffmielke** [comment]
@msonderegger and @MichaelGoodale Sorry I was thinking of 3 vs. 9
measurement points instead of 3 vs. 9 tracks. If you take the measurements
directly from the Formant object, they will be at 0.01s intervals, meaning
the number of measurements will depend on the duration of each segment.
That probably isn't good. Usually I pick a fixed number of measurement
points and use Get value at time... to get an interpolated value at each
time. That is what we are currently doing in order to measure every vowel
at 0.33. Note that the current multiple_num_formants.praat extracts the
vowel without any padding, meaning that we cannot extract values from near
the edge of the vowel. If we extract an additional 0.025 at the start and
end of the vowel, we should be able to measure any point in the vowel
including 0% and 100%.



Jeff Mielke
Associate professor
Linguistics program
Department of English
North Carolina State University

**Pull request merged**
